version: "3"
services:
  backend:
    image: ghcr.io/bthzang/aqa-backend-nestjs/aqa-be:${VERSION}
    restart: always
    env_file:
      - .env
    links:
      - postgres
    networks:
      - aqa

  postgres:
    image: postgres:16.3
    container_name: postgres
    restart: always
    volumes:
      - /database:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - aqa

  adminer:
    image: adminer:4.8.1
    container_name: adminer
    restart: always
    depends_on:
      - postgres
    networks:
      - aqa
  
  webserver:
    image: nginx:latest
    container_name: webserver
    restart: always
    depends_on:
      - backend
    ports:
      - 80:80
      - 443:443
    # command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    volumes:
      - ./webserver/nginx/app.conf:/etc/nginx/sites-available/bthzang.id.vn:ro
      - /etc/letsencrypt/live/bthzang.id.vn/:/etc/letsencrypt/live/bthzang.id.vn/:ro 
      # - ./webserver/certbot/www:/var/www/certbot:ro
    networks:
      - aqa

  certbot:
    image: certbot/certbot:v2.10.0
    container_name: certbot
    # entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    # volumes:
      # - ./webserver/certbot/conf:/etc/letsencrypt:rw
      # - ./webserver/certbot/www:/var/www/certbot:rw
    networks:
      - aqa

networks:
  aqa:
    driver: bridge
